# version of docker-compose
version: "3.9"
# 'services' are equivalent to 'containers'
services:
  redis-stack-server:
    # Use Docker Hub base image 'redis:alpine'
    image: "redis/redis-stack-server"
  serverapp:
    restart: always
    build: ./
    volumes:
      - C:\Users\HP\Desktop\insta\API:/server
      - /server/node_modules
    # Specify an array of ports to map
    ports:
      - "8000:8000"
      - "3000:3000"
